Link to dataset : https://drive.google.com/file/d/1sbQ5WJ-KCPBrhT2YagtaARGoujCMpB8Q/view

# SA-2025 WEEK 3 GRADED ASSIGNMENT

> Spaceship Titanic

Predict which passengers are transported to an alternate dimension

![](https://www.gannett-cdn.com/-mm-/682bf77435754aee88576469063388a7d8b07c2a/c=0-150-1280-873/local/-/media/2017/02/01/Reno/RGJ/636215634914521096-image001.jpg?width=660&height=373&fit=crop&[...]

### <b>Description</b>

Welcome to the year 2912, where your data science skills are needed to solve a cosmic mystery. We've received a transmission from four lightyears away and things aren't looking good.

The Spaceship Titanic was an interstellar passenger liner launched a month ago. With almost 13,000 passengers on board, the vessel set out on its maiden voyage transporting emigrants from our[...]
While rounding Alpha Centauri en route to its first destination—the torrid 55 Cancri E—the unwary Spaceship Titanic collided with a spacetime anomaly hidden within a dust cloud. Sadly, it[...]

### <b>Data description</b>

- Personal records for about two-thirds (~8700) of the passengers, to be used as training data.
- <code>PassengerId</code> - A unique Id for each passenger. Each Id takes the form gggg_pp where gggg indicates a group the passenger is travelling with and pp is their number within the gro[...]
- <code>HomePlanet</code> - The planet the passenger departed from, typically their planet of permanent residence.
- <code>CryoSleep</code> - Indicates whether the passenger elected to be put into suspended animation for the duration of the voyage. Passengers in cryosleep are confined to their cabins.
- <code>Cabin</code> - The cabin number where the passenger is staying. Takes the form deck/num/side, where side can be either P for Port or S for Starboard.
- <code>Destination</code> - The planet the passenger will be debarking to.
- <code>Age</code> - The age of the passenger.
- <code>VIP</code> - Whether the passenger has paid for special VIP service during the voyage.
- <code>RoomService, FoodCourt, ShoppingMall, Spa, VRDeck</code> - Amount the passenger has billed at each of the Spaceship Titanic's many luxury amenities.
- <code>Name</code> - The first and last names of the passenger.
- <code>Transported</code> - Whether the passenger was transported to another dimension. This is the target, the column you are trying to predict.

### <b>Algorithm Documentation</b> (Highly recommended!)
- <code>Logistic Regression</code> : https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
- <code>SVM</code> : https://scikit-learn.org/stable/modules/svm.html
Confusion Matrix : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
- <code>Plot Confusion Matrix</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.plot_confusion_matrix.html
- <code>ROC_AUC Score</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score
- <code>Classification Report</code> : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
- <code>Label Encoder</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
- <code>Label Binarizer</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html
- <code>Standard Scaler</code> : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- <code>Cross Val Score</code> : https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html

# <span><h1 style = "font-family: garamond; font-size: 40px; font-style: normal; letter-spcaing: 3px; background-color: #f6f5f5; color :#fe346e; border-radius: 100px 100px; text-align:center[...]

In [873]:
!pip install --upgrade scikit-learn  #There was an error with importing confusion_matrix from sklearn.mertices , so there was a need to upgrade it for google colab
# even after upgrading the plot_confusion_matrix didnt worked as it has been changed in new version

ERROR: Invalid requirement: '#There': Expected package name at the start of dependency specifier
    #There
    ^

In [874]:
## ======== YOUR CODE HERE ======== ##
# Install packages if needed
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import svm
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import root_mean_squared_error , classification_report,roc_auc_score,confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder,label_binarize
from sklearn.ensemble import RandomForestRegressor



import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

#### Read the data

In [875]:
df = pd.read_csv("data.csv")
df.head()

#### Check the shape of data. It should be  (8693, 14)

In [876]:
## ======== YOUR CODE HERE ======== ##
df.shape

## ================================ ##

(8693, 14)

#### Apply describe on dataframe

In [877]:
## ======== YOUR CODE HERE ======== ##
df.describe

#
## ================================ ##

<bound method NDFrame.describe of      PassengerId HomePlanet  CryoSleep     Cabin Destination  Age    VIP  \
0        0001_01     Europa      False     B/0/P   Andromeda   39  False
1        0002_01      Earth      False     F/0/S   Andromeda   24  False
2        0003_01     Europa      False     A/0/S   Andromeda   58   True
3        0003_02     Europa      False     A/0/S   Andromeda   33  False
4        0004_01      Earth      False     F/1/S   Andromeda   16  False
...          ...        ...        ...       ...         ...  ...    ...
8688     9276_01     Europa      False    A/98/P       Virgo   41   True
8689     9278_01      Earth       True  G/1499/S      Cygnus   18  False
8690     9279_01      Earth      False  G/1500/S   Andromeda   26  False
8691     9280_01     Europa      False   E/608/S       Virgo   32  False
8692     9280_02     Europa      False   E/608/S   Andromeda   44  False

      RoomService  FoodCourt  ShoppingMall   Spa  VRDeck               Name  \
0               0          0             0     0       0    Maham Ofracculy
1             109          9            25   549      44       Juanna Vines
2              43       3576             0  6715      49      Altark Susent
3               0       1283           371  3329     193       Solam Susent
4             303         70           151   565       2  Willy Santantines
...           ...        ...           ...   ...     ...                ...
8688            0       6819             0  1643      74  Gravior Noxnuther
8689            0          0             0     0       0    Kurta Mondalley
8690            0          0          1872     1       0       Fayey Connon
8691            0       1049             0   353    3235   Celeon Hontichre
8692          126       4688             0     0      12   Propsh Hontichre

      Transported
0           False
1            True
2           False
3           False
4            True
...           ...
8688        False
8689        False
8690         True
8691        False
8692         True

[8693 rows x 14 columns]>

#### Check if there any null value in the dataset.

In [878]:
## ======== YOUR CODE HERE ======== ##
df.isna().sum()
#no null values in the dataset
df.head()



## ================================ ##

#### Number continuous and categorical features

In [879]:
#################################################################

# Don't make mistake here. Ask in the discussion section if you are stuck. Help will be provided....

#################################################################

## ======== YOUR CODE HERE ======== ##
categorical_features = df.select_dtypes(include=['object']).columns


## ======== YOUR CODE HERE ======== ##
continuous_features = df.select_dtypes(include=['int64', 'float64']).columns
print(categorical_features.value_counts())
print(continuous_features.value_counts())
len(categorical_features), len(continuous_features)
df.head()

PassengerId    1
HomePlanet     1
Cabin          1
Destination    1
Name           1
Name: count, dtype: int64
Age             1
RoomService     1
FoodCourt       1
ShoppingMall    1
Spa             1
VRDeck          1
Name: count, dtype: int64